# -*- coding: utf-8 -*-
"""
DHARMA KEYS — PDF GENERATION SERVICE
Awakened Academy / Liberated Life LLC

Renders a personalised Dharma Keys reading PDF in the Awakened Academy brand
(cream parchment, Fraunces + Inter, teal + gold). One engine, two lengths:

  - FREE reading : Opening + 3 Keys (Energy, Shadow, Power) + "Your Next Step"
  - FULL reading : Opening + up to 10 Keys + "The Blessing"

The free reading is the opening of the full reading, stopped early — same
chart, same named patterns, same voice, same design.

PIPELINE
  Make.com opt-in (name, birth data)
    -> chart calculated, reading text generated by the Claude step
    -> POST to this service  ->  branded PDF returned
    -> emailed to the reader

ENDPOINTS
  POST /generate-file   -> application/pdf  (use this from Make.com)
  POST /generate        -> {"pdf_base64": "...", "filename": "..."}
  GET  /health

POST body (JSON):
  {
    "name":         "Michael",
    "birth_date":   "6 March 1979",
    "birth_time":   "8:07 PM",
    "birth_place":  "Grahamstown, South Africa",
    "tier":         "free",          # "free" or "full"
    "reading_text": "=== OPENING ===\\n..."
  }

reading_text FORMAT (what the Claude step produces):

  === OPENING ===
  <paragraphs, blank-line separated>
  [[LEAD]] <one closing lead-style line>

  === KEY: Your Energy Key | You Run in Tides ===
  <paragraphs>
  ## <optional subheading inside the Key>
  <paragraphs>
  === QUESTION ===
  <one contemplation question>

  === KEY: Your Shadow Key | The Finished Picture & The Lone Deep ===
  ...

  === BLESSING ===            (full reading only — omit for the free reading)
  <paragraphs>
  [[LEAD]] <closing lead line>
  [[SIGN]] Lots of love, and walk well.

The cover, the short intro, the per-Key "What this Key is" notes and the
free reading's "Your Next Step" are fixed in this file — only the Opening,
the Keys and the Blessing are personalised.
"""

import io
import re
import base64
from flask import Flask, request, jsonify, make_response
from weasyprint import HTML

app = Flask(__name__)

# ---------------------------------------------------------------- brand CSS
CSS = """
@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400;1,9..144,500&family=Inter:wght@400;500;600;700&display=swap');
:root{
  --amethyst:#6B2D8E; --amethyst-deep:#4A1F66; --amethyst-soft:#9B6BBA;
  --gold:#C9A04C; --gold-deep:#9F7E38; --gold-pale:#E8D4A0;
  --cream:#ECE4EA; --cream-paper:#F4EEF1;
  --ink:#0F0A06; --ink-soft:rgba(15,10,6,0.80); --ink-muted:rgba(15,10,6,0.60);
  --rose:#C47E7E; --line:rgba(74,31,102,0.18);
  --serif:'Fraunces','Lora','Georgia',serif;
  --sans:'Inter','Liberation Sans','DejaVu Sans',sans-serif;
}
@page{
  size:Letter; margin:19mm 21mm 16mm; background:#ECE4EA;
  @bottom-center{ content:counter(page);
    font-family:'Inter','Liberation Sans',sans-serif;
    font-size:8pt; color:rgba(15,10,6,0.45); letter-spacing:.12em; }
}
@page:first{ margin:0; background:#ECE4EA; @bottom-center{content:""} }
html{ background:#ECE4EA; }
body{ font-family:var(--sans); color:var(--ink); font-size:11.4pt;
  line-height:1.72; margin:0; background:#ECE4EA; }
p{ margin:0 0 11pt; }
.eyebrow{ font-family:var(--sans); font-size:8.5pt; font-weight:600;
  letter-spacing:.3em; text-transform:uppercase; color:var(--gold-deep);
  text-align:center; margin-bottom:6pt; }
.sparkle{ text-align:center; color:var(--gold); font-size:13pt; margin:9pt 0 15pt; }
h2.title{ font-family:var(--serif); font-weight:500; color:var(--ink);
  font-size:27pt; line-height:1.12; text-align:center;
  letter-spacing:-.01em; margin:0; }
.pattern{ font-family:var(--serif); font-style:italic; font-weight:500;
  color:var(--gold-deep); font-size:15pt; text-align:center; margin:7pt 0 0; }
.explainer{ background:var(--cream-paper); border-left:3px solid var(--amethyst);
  padding:13pt 16pt 11pt; margin:0 0 20pt; }
.explainer .lab{ font-family:var(--sans); font-size:8pt; font-weight:600;
  letter-spacing:.22em; text-transform:uppercase; color:var(--amethyst);
  margin-bottom:5pt; }
.explainer p{ font-size:10.6pt; line-height:1.66; color:var(--ink-soft); margin:0; }
.sub{ font-family:var(--sans); font-size:9.5pt; font-weight:600;
  letter-spacing:.13em; text-transform:uppercase; color:var(--amethyst);
  margin:17pt 0 7pt; }
.lead{ font-family:var(--serif); font-style:italic; font-size:14pt;
  line-height:1.5; color:var(--ink); margin:14pt 0 0; }
.contempl{ border-top:1px solid var(--gold-pale); margin-top:17pt; padding-top:11pt; }
.contempl .qlab{ font-family:var(--sans); font-size:8pt; font-weight:600;
  letter-spacing:.2em; text-transform:uppercase; color:var(--rose);
  display:block; margin-bottom:4pt; }
.contempl p{ font-family:var(--serif); font-style:italic; font-size:11.6pt;
  line-height:1.56; color:var(--ink-soft); margin:0; }
section{ page-break-before:always; }
.section-head{ margin-bottom:2pt; }
.cover{ page-break-before:avoid; page-break-after:always; height:248mm;
  padding:0 30mm; display:flex; flex-direction:column;
  align-items:center; justify-content:center; text-align:center; }
.cover .mark{ margin-bottom:20pt; }
.cover h1{ font-family:var(--serif); font-weight:400; color:var(--amethyst-deep);
  font-size:41pt; letter-spacing:.04em; line-height:1.1; margin:0; }
.cover .for{ font-family:var(--serif); font-style:italic; font-size:19pt;
  color:var(--amethyst); margin:16pt 0 0; }
.cover .cover-rule{ width:54pt; border:0; border-top:1px solid var(--gold);
  margin:26pt 0 24pt; }
.cover .meta{ font-family:var(--sans); font-size:9.5pt; line-height:1.85;
  color:var(--ink-muted); letter-spacing:.04em; }
.cover .meta .bk{ font-style:normal; color:var(--gold-deep); }
.opening-body p{ font-size:11.8pt; line-height:1.76; }
.intro p{ font-size:11.4pt; }
.keylist{ margin:13pt 0 4pt; }
.keylist .row{ padding:6.5pt 0; border-top:1px solid var(--line);
  font-size:10.6pt; line-height:1.5; }
.keylist .row:last-child{ border-bottom:1px solid var(--line); }
.keylist .kn{ font-family:var(--serif); font-style:italic; color:var(--amethyst);
  font-size:11.6pt; font-weight:500; }
.keylist .kg{ color:var(--ink-soft); }
.cta-band{ background:var(--cream-paper); border:1px solid var(--gold-pale);
  border-left:3px solid var(--gold); padding:18pt 20pt; margin:18pt 0 0; }
.cta-band .big{ font-family:var(--serif); font-size:15pt; color:var(--ink);
  font-weight:500; margin:0 0 6pt; }
.cta-band p{ font-size:10.8pt; color:var(--ink-soft); margin:0 0 7pt; }
.cta-band .go{ font-family:var(--sans); font-size:10.5pt; font-weight:600;
  color:var(--amethyst); margin:9pt 0 0; }
.statline{ text-align:center; font-family:var(--sans); font-size:8.5pt;
  letter-spacing:.12em; color:var(--ink-muted); margin-top:22pt;
  border-top:1px solid var(--line); padding-top:12pt; }
.statline b{ color:var(--gold-deep); font-weight:600; }
.signoff{ font-family:var(--serif); font-style:italic; font-size:12.5pt;
  color:var(--ink); margin-top:16pt; }
"""

# the gold mandala mark used on the cover (inline SVG)
COVER_MARK = (
    '<svg class="mark" width="58" height="58" viewBox="0 0 58 58" aria-hidden="true">'
    '<g fill="none" stroke="#C9A04C" stroke-width="0.9">'
    '<circle cx="29" cy="29" r="25"/><circle cx="29" cy="29" r="17"/>'
    '<circle cx="29" cy="29" r="9"/></g>'
    '<path d="M29 14 L31 27 L44 29 L31 31 L29 44 L27 31 L14 29 L27 27 Z" fill="#C9A04C"/>'
    '</svg>'
)
SPARK = "&#10022;"

# ------------------------------------------------ fixed per-Key explainers
KEY_EXPLAINERS = {
 "Your Energy Key":
   "The first thing to know about anyone is how they are built to run. Your "
   "Energy Key names your natural rhythm — when you have power and when you "
   "do not, what fills your tank and what empties it. It also names the make of "
   "your energy and the quality it carries, and what you look like at your best "
   "and when you have drifted off course.",
 "Your Shadow Key":
   "The book calls your true self a diamond that has been trampled into the "
   "mud. Your Shadow Key names the mud — the patterns that quietly run your "
   "life from underneath, the blind spots that are almost impossible to see in "
   "yourself. It is the hardest Key to read, and the most valuable. Every "
   "shadow named here also hides a gift, and the Key names that too.",
 "Your Power Key":
   "You arrived with gifts — real ones, not vague potential. Your Power Key "
   "names the three you can build a whole life on, including the ones you have "
   "dismissed because they come too easily to feel like gifts. One of the three "
   "is your Diamond: the single gift the world will most value, and most pay "
   "you for.",
 "Your Connection Key":
   "Relationships, the book says, hold the greatest power of all eight levels "
   "of life — the power to lift you, or to drain you. Your Connection Key "
   "shows how you are wired for people: how much solitude you genuinely need, "
   "who refills you, who empties you, and the social blind spot that quietly "
   "costs you.",
 "Your Source Key":
   "For a spiritual person, the relationship with God, Source, the divine is "
   "the foundation everything else rests on. Your Source Key reveals your own "
   "specific doorway home — how you, personally, are wired to reach that "
   "connection, what swings the door open, and what quietly closes it.",
 "Your Life Levels":
   "The book describes a whole life as eight connected levels — your spirit, "
   "your mind, your emotions, your actions, your body, your environment, your "
   "relationships, and your money. Your Life Levels is an honest look across "
   "all eight at once: which sit well above the water line, and which are "
   "sitting close to it and asking for your attention.",
 "Your Success Key":
   "This Key names your Sva-Dharma — your own dharma, the work that is yours "
   "and no one else’s. The book maps it as four circles: your passion, your "
   "skills, the people you serve, and your unique service to them. Your Success "
   "Key reads all four from your chart, and names the work, the people, the "
   "bottleneck, and the one move that matters most.",
 "Your Money Key":
   "Wealth is one of the eight levels of a whole life — and the book is clear "
   "that poverty is not a spiritual virtue. Your Money Key looks honestly at "
   "money: how you are built to earn, the money story you inherited before you "
   "could choose it, the shadow pattern that has quietly capped you, how you "
   "are wired to receive, and your real path to wealth.",
 "Your Path Forward":
   "A reading that shows you who you are without telling you what to do leaves "
   "a gap. Your Path Forward closes it — a small number of concrete moves, "
   "each one aimed at a specific Key in this reading, each one small enough to "
   "begin this week.",
 "Your Timing Key":
   "The book teaches that timing is real — there are seasons to build and "
   "seasons to rest, and wisdom is knowing which one you are in. Your Timing "
   "Key shows the chapter of life you are standing in right now, and what the "
   "next twelve months are asking of you.",
}

ORDINALS = ["One", "Two", "Three", "Four", "Five",
            "Six", "Seven", "Eight", "Nine", "Ten"]

# the seven Keys held back from the free reading (used in "Your Next Step")
HELD_BACK = [
    ("Your Connection Key",  "how you are wired for people"),
    ("Your Source Key",      "your own doorway to the divine"),
    ("Your Life Levels",     "an honest look across all eight levels of your life"),
    ("Your Success Key",     "the work that is yours, and no one else’s"),
    ("Your Money Key",       "how money is truly built to flow for you"),
    ("Your Path Forward",    "the concrete moves to make next"),
    ("Your Timing Key",      "the chapter you are standing in, and what is coming"),
]


# ----------------------------------------------------------- typography
def sm(s):
    """Straight quotes -> smart quotes; -- -> em dash."""
    s = s.replace("---", "—").replace(" -- ", " — ")
    s = re.sub(r'(\w)\'(\w)', '’'.join(['\\1', '\\2']), s)
    s = re.sub(r'(?<=\w)\'', '’', s)
    s = re.sub(r'\'(?=\w)', '‘', s)
    s = s.replace('"', '“', 1) if s.count('"') >= 2 else s
    return s


def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def tidy(s):
    """Escape, then apply smart apostrophes (no HTML in reading text)."""
    s = esc(s)
    s = s.replace("'", "’")
    return s


# ----------------------------------------------------------- parser
def parse_reading(text):
    """Parse reading_text into an ordered list of blocks."""
    blocks = []
    cur = None
    qmode = False

    def flush():
        nonlocal cur
        if cur is not None:
            blocks.append(cur)
        cur = None

    for raw in text.splitlines():
        line = raw.rstrip()
        m = re.match(r'^===\s*(.+?)\s*===\s*$', line.strip())
        if m:
            tag = m.group(1)
            up = tag.upper()
            if up == "QUESTION":
                qmode = True
                continue
            qmode = False
            flush()
            if up.startswith("KEY:"):
                rest = tag[4:].strip()
                if "|" in rest:
                    title, pattern = [p.strip() for p in rest.split("|", 1)]
                else:
                    title, pattern = rest, ""
                cur = {"type": "key", "title": title, "pattern": pattern,
                       "parts": [], "question": ""}
            elif up == "OPENING":
                cur = {"type": "opening", "parts": []}
            elif up == "BLESSING":
                cur = {"type": "blessing", "parts": []}
            elif up == "CLOSE":
                cur = {"type": "close", "parts": []}
            elif up in ("INTRO", "NEXT STEP", "NEXTSTEP"):
                cur = {"type": "skip", "parts": []}   # fixed in template
            else:
                cur = {"type": "opening", "parts": []}
            continue
        if cur is None:
            continue
        if qmode and cur.get("type") == "key":
            if line.strip():
                cur["question"] = (cur["question"] + " " + line.strip()).strip()
            continue
        cur["parts"].append(line)

    flush()
    return blocks


def to_paragraphs(parts):
    """Turn raw lines into [(kind, text)] — kind = 'sub' | 'lead' | 'para'."""
    out = []
    buf = []

    def push():
        if buf:
            txt = " ".join(x.strip() for x in buf).strip()
            if txt:
                if txt.startswith("[[LEAD]]"):
                    out.append(("lead", txt[8:].strip()))
                else:
                    out.append(("para", txt))
        buf.clear()

    for ln in parts:
        s = ln.strip()
        if not s:
            push()
        elif s.startswith("## "):
            push()
            out.append(("sub", s[3:].strip()))
        else:
            buf.append(s)
    push()
    return out


# ----------------------------------------------------------- HTML builders
def render_cover(name, birth_line, tier):
    sub = ("Who you are · the gift you carry · the pattern in your way"
           if tier == "free" else "The complete reading · all ten Keys")
    return f"""
<div class="cover">
  {COVER_MARK}
  <h1>YOUR DHARMA KEYS</h1>
  <div class="for">A personal reading for {esc(name)}</div>
  <hr class="cover-rule">
  <div class="meta">
    {esc(sub)}<br>
    Based on <span class="bk">The Dharma Keys</span> by Michael Mackintosh<br>
    {esc(birth_line)}<br>
    Awakened Academy&reg;
  </div>
</div>
"""


def render_intro(name, tier):
    if tier == "free":
        body = (
            f"<p><strong>Hi {esc(name)},</strong></p>"
            "<p>Your Dharma Keys reading is ready.</p>"
            "<p>This reading was built from your birth chart &mdash; the exact "
            "map of the sky at the moment and the place you were born &mdash; "
            "and the dharma framework from Michael Mackintosh&rsquo;s book, "
            "<em>The Dharma Keys</em>. Every word in it is about you specifically.</p>"
            "<p>By the time you finish, you will understand who you are as a guide, "
            "the gifts you carry, and the one pattern that has been quietly in your "
            "way &mdash; including the way it has shaped your income.</p>"
            "<p>Read it slowly. Find somewhere you will not be interrupted.</p>"
            "<p><em>There is no one else on earth with your chart.</em></p>"
        )
    else:
        body = (
            f"<p>Hi {esc(name)},</p>"
            "<p>This is your full Dharma Keys reading — all ten Keys, built "
            "from your birth chart and the dharma framework from Michael "
            "Mackintosh’s book, <em>The Dharma Keys</em>.</p>"
            "<p>Each Key unlocks a different room of you. Read it slowly, and "
            "come back to it — it is built to be returned to.</p>"
        )
    return f"""
<section>
  <div class="section-head">
    <div class="eyebrow">Before You Begin</div>
    <h2 class="title">Your Dharma Keys</h2>
  </div>
  <div class="sparkle">{SPARK}</div>
  <div class="intro">{body}</div>
</section>
"""


def render_paras(paras, lead_class="lead", body_class=""):
    html = []
    for kind, txt in paras:
        if kind == "sub":
            html.append(f'<div class="sub">{tidy(txt)}</div>')
        elif kind == "lead":
            html.append(f'<p class="{lead_class}">{tidy(txt)}</p>')
        else:
            cls = f' class="{body_class}"' if body_class else ""
            html.append(f"<p{cls}>{tidy(txt)}</p>")
    return "\n".join(html)


def render_opening(block, tier="full"):
    paras = to_paragraphs(block["parts"])
    # drop a leading line that just repeats the title
    if paras and paras[0][1].lower().startswith("your dharma in one breath"):
        paras = paras[1:]
    if tier == "free":
        eyebrow = "Your Personal Reading"
        title = "You Are an Awakened Guide"
    else:
        eyebrow = "Opening"
        title = "Your Dharma in One Breath"
    return f"""
<section>
  <div class="section-head">
    <div class="eyebrow">{eyebrow}</div>
    <h2 class="title">{title}</h2>
  </div>
  <div class="sparkle">{SPARK}</div>
  <div class="opening-body">
    {render_paras(paras)}
  </div>
</section>
"""


def render_key(block, index, tier="full"):
    title = block["title"]
    pattern = block.get("pattern", "")
    explainer = KEY_EXPLAINERS.get(title, "")
    if tier == "free":
        # Free reading uses content-based eyebrows mirroring v6 manual reading
        FREE_LABELS = {
            "Your Energy Key": ("Your Energy", "Your Energy"),
            "Your Power Key":  ("Your Gifts", "Your Superpowers"),
            "Your Shadow Key": ("Your Shadow", "Your Shadow Key"),
        }
        if title in FREE_LABELS:
            eyebrow, title = FREE_LABELS[title]
            eyebrow_html = f'<div class="eyebrow">{eyebrow}</div>'
        else:
            eyebrow_html = ""
    else:
        eyebrow = "Key " + (ORDINALS[index] if index < len(ORDINALS) else str(index + 1))
        eyebrow_html = f'<div class="eyebrow">{eyebrow}</div>'
    pattern_html = f'<div class="pattern">{tidy(pattern)}</div>' if pattern else ""
    explainer_html = ""
    if explainer:
        explainer_html = (
            '<div class="explainer"><div class="lab">What this Key is</div>'
            f"<p>{explainer}</p></div>"
        )
    body = render_paras(to_paragraphs(block["parts"]))
    q = block.get("question", "").strip()
    q_html = ""
    if q:
        q_html = (
            '<div class="contempl"><span class="qlab">A question to sit with</span>'
            f"<p>{tidy(q)}</p></div>"
        )
    return f"""
<section>
  <div class="section-head">
    {eyebrow_html}
    <h2 class="title">{esc(title)}</h2>
    {pattern_html}
  </div>
  <div class="sparkle">{SPARK}</div>
  {explainer_html}
  {body}
  {q_html}
</section>
"""


def render_blessing(block):
    paras = to_paragraphs(block["parts"])
    html = []
    for kind, txt in paras:
        if kind == "lead":
            html.append(f'<p class="lead">{tidy(txt)}</p>')
        elif txt.startswith("[[SIGN]]"):
            html.append(f'<p class="signoff">{tidy(txt[8:].strip())}</p>')
        else:
            html.append(f"<p>{tidy(txt)}</p>")
    return f"""
<section>
  <div class="section-head">
    <div class="eyebrow">Closing</div>
    <h2 class="title">The Blessing</h2>
  </div>
  <div class="sparkle">{SPARK}</div>
  {''.join(html)}
  <div style="text-align:center;margin-top:30pt;color:#C9A04C;font-size:12pt;">{SPARK}</div>
</section>
"""


def render_close(block):
    """The free reading's close — 'What You Need' + Sacred Session + paid upgrade."""
    personal = render_paras(to_paragraphs(block["parts"]))
    return f"""
<section>
  <div class="section-head">
    <div class="eyebrow">Your Next Step</div>
    <h2 class="title">What You Need</h2>
  </div>
  <div class="sparkle">{SPARK}</div>
  {personal}
  <div class="cta-band">
    <p class="big">A free Sacred Dharma Session.</p>
    <p>Thirty minutes, one-to-one, built entirely from your chart and your life.
    Nothing generic. You leave knowing what your gifts are worth, and exactly
    what to do first.</p>
    <p class="go"><a href="https://awakenedacademy.com/schedule" style="color:var(--amethyst);text-decoration:none;border-bottom:1.5px solid var(--amethyst);">Book your session at awakenedacademy.com/schedule &rarr;</a></p>
  </div>
  <div style="margin:18pt 0 0;padding:16pt 0 0;border-top:1px solid var(--line);">
    <p style="font-family:var(--sans);font-size:9.5pt;font-weight:600;letter-spacing:.18em;text-transform:uppercase;color:var(--gold-deep);margin:0 0 7pt;">Or &mdash; Go Deeper On Your Own First</p>
    <p style="font-family:var(--serif);font-size:14pt;color:var(--ink);font-style:italic;margin:0 0 6pt;">The Full Dharma Keys Reading.</p>
    <p style="font-size:11.5pt;color:var(--ink-soft);margin:0 0 6pt;line-height:1.55;">All ten Keys: your wealth pattern, your relationship pattern, your timing through the next twelve months, and the closing Blessing. Twenty-seven pages, $17, in your inbox within 24 hours.</p>
    <p style="font-family:var(--sans);font-size:11pt;font-weight:600;color:var(--gold-deep);margin:8pt 0 0;"><a href="https://awakenedacademy.com/dharma-code" style="color:var(--gold-deep);text-decoration:none;border-bottom:1.5px solid var(--gold);">Get the full reading &rarr;</a></p>
  </div>
  <p class="statline"><b>650+</b> certified coaches &nbsp;&middot;&nbsp;
  <b>25+</b> countries &nbsp;&middot;&nbsp;
  <b>85,000+</b> five-star reviews &nbsp;&middot;&nbsp;
  teaching since 2012</p>
</section>
"""


# ----------------------------------------------------------- assembly
def build_html(name, birth_date, birth_time, birth_place, reading_text, tier):
    birth_bits = [birth_date]
    if birth_time and birth_time.lower() not in ("", "unknown"):
        birth_bits.append(birth_time)
    if birth_place:
        birth_bits.append(birth_place)
    birth_line = "  ·  ".join(birth_bits)

    blocks = parse_reading(reading_text)
    body = [render_cover(name, birth_line, tier), render_intro(name, tier)]

    key_i = 0
    for b in blocks:
        if b["type"] == "opening":
            body.append(render_opening(b, tier))
        elif b["type"] == "key":
            body.append(render_key(b, key_i, tier))
            key_i += 1
        elif b["type"] == "blessing":
            body.append(render_blessing(b))
        elif b["type"] == "close":
            body.append(render_close(b))

    return (
        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\">"
        f"<title>Your Dharma Keys — {esc(name)}</title>"
        f"<style>{CSS}</style></head><body>{''.join(body)}</body></html>"
    )


def build_pdf(name, birth_date, birth_time, birth_place, reading_text, tier="free"):
    """Render the branded Dharma Keys PDF. Returns bytes."""
    html = build_html(name, birth_date, birth_time, birth_place,
                       reading_text, tier)
    buf = io.BytesIO()
    HTML(string=html).write_pdf(buf)
    buf.seek(0)
    return buf.read()


# ----------------------------------------------------------- Flask endpoints
def _read_request():
    data = request.get_json(silent=True)
    if not data:
        return None, (jsonify({"error": "No JSON body"}), 400)
    for field in ("name", "birth_date", "reading_text"):
        if field not in data:
            return None, (jsonify({"error": f"Missing field: {field}"}), 400)
    return {
        "name": data["name"],
        "birth_date": data.get("birth_date", ""),
        "birth_time": data.get("birth_time", "unknown"),
        "birth_place": data.get("birth_place", ""),
        "reading_text": data["reading_text"],
        "tier": (data.get("tier", "free") or "free").lower(),
    }, None


@app.route("/generate-file", methods=["POST"])
def generate_file():
    """Returns the PDF as a direct file download — use this from Make.com."""
    d, err = _read_request()
    if err:
        return err
    try:
        pdf = build_pdf(d["name"], d["birth_date"], d["birth_time"],
                        d["birth_place"], d["reading_text"], d["tier"])
        slug = d["name"].lower().replace(" ", "-")
        fn = f"dharma-keys-{d['tier']}-reading-{slug}.pdf"
        resp = make_response(pdf)
        resp.headers["Content-Type"] = "application/pdf"
        resp.headers["Content-Disposition"] = f'attachment; filename="{fn}"'
        resp.headers["Content-Length"] = str(len(pdf))
        return resp
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/generate", methods=["POST"])
def generate():
    """Returns the PDF as base64 JSON (legacy)."""
    d, err = _read_request()
    if err:
        return err
    try:
        pdf = build_pdf(d["name"], d["birth_date"], d["birth_time"],
                        d["birth_place"], d["reading_text"], d["tier"])
        slug = d["name"].lower().replace(" ", "-")
        return jsonify({
            "pdf_base64": base64.b64encode(pdf).decode("utf-8"),
            "filename": f"dharma-keys-{d['tier']}-reading-{slug}.pdf",
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "service": "Dharma Keys PDF Generator"})


# ----------------------------------------------------------- local test
if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "--test":
        # render a sample from a local input file
        infile = sys.argv[2] if len(sys.argv) > 2 else "free-reading-input.txt"
        outfile = sys.argv[3] if len(sys.argv) > 3 else "test-reading.pdf"
        tier = sys.argv[4] if len(sys.argv) > 4 else "free"
        with open(infile, encoding="utf-8") as fh:
            txt = fh.read()
        pdf = build_pdf("Michael", "6 March 1979", "8:07 PM",
                        "Grahamstown, South Africa", txt, tier)
        with open(outfile, "wb") as fh:
            fh.write(pdf)
        print(f"wrote {outfile} ({len(pdf):,} bytes)")
    else:
        app.run(host="0.0.0.0", port=8080)
